# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signUpPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 712)
        MainWindow.setMinimumSize(QtCore.QSize(1124, 712))
        MainWindow.setMaximumSize(QtCore.QSize(1124, 712))
        MainWindow.setStyleSheet("\n"
"*{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    background: transparent;\n"
"    padding:0;\n"
"    margin:0;\n"
"    color:#fff;\n"
"}\n"
"\n"
"#centralwidget{\n"
"\n"
"    background-color: rgb(87, 0, 130);\n"
"\n"
"}\n"
"\n"
"#widget{\n"
"    \n"
"    border-radius: 20px;\n"
"    background-color: rgb(14, 16, 23);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    \n"
"    padding: 5px 3px;\n"
"    background-color: rgba(0, 192, 239, 100);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    padding: 5px 3px;\n"
"    background-color: rgba(0, 192, 239);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(0, 192, 239);\n"
"    padding: 10px 5px;\n"
"    border-radius: 5px;\n"
"    color: rgb(245, 245, 255);\n"
"}\n"
"\n"
"#to_login, #to_register{\n"
"    background-color:transparent;\n"
"\n"
"}\n"
"\n"
"#register_pushButton:hover {\n"
"    \n"
"    background-color: rgb(87, 0, 130);\n"
"}\n"
"\n"
"#login_pushButton:hover {\n"
"    \n"
"    background-color: rgb(87, 0, 130);\n"
"\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.header_frame.setStyleSheet("#header_frame{\n"
"    border-bottom: 1px solid;\n"
"    border-bottom-color: rgb(14, 16, 23);\n"
"\n"
"}\n"
"\n"
"")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.top_left_btns = QtWidgets.QFrame(self.header_frame)
        self.top_left_btns.setStyleSheet("QPushButton{\n"
"    background-color:none;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 192, 239);\n"
"    border-radius:10px;\n"
"}")
        self.top_left_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_left_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_left_btns.setObjectName("top_left_btns")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_left_btns)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minimize_pushButton = QtWidgets.QPushButton(self.top_left_btns)
        self.minimize_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon-w/minimize-w.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_pushButton.setIcon(icon)
        self.minimize_pushButton.setObjectName("minimize_pushButton")
        self.horizontalLayout.addWidget(self.minimize_pushButton, 0, QtCore.Qt.AlignTop)
        self.close_pushButton = QtWidgets.QPushButton(self.top_left_btns)
        self.close_pushButton.setStyleSheet("")
        self.close_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon-w/close-w.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_pushButton.setIcon(icon1)
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout.addWidget(self.close_pushButton, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.top_left_btns, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.header_frame, 0, QtCore.Qt.AlignTop)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(350, 600))
        self.widget.setMaximumSize(QtCore.QSize(350, 500))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.registerPage = QtWidgets.QWidget()
        self.registerPage.setObjectName("registerPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.registerPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.registerPage)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/profile-w.png"))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.registerPage)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(245, 245, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3 = QtWidgets.QLabel(self.registerPage)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.registerPage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.name_lineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.name_lineEdit.setFont(font)
        self.name_lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.name_lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.verticalLayout_4.addWidget(self.name_lineEdit)
        self.surname_lineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.surname_lineEdit.setFont(font)
        self.surname_lineEdit.setObjectName("surname_lineEdit")
        self.verticalLayout_4.addWidget(self.surname_lineEdit)
        self.register_email_lineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.register_email_lineEdit.setFont(font)
        self.register_email_lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.register_email_lineEdit.setObjectName("register_email_lineEdit")
        self.verticalLayout_4.addWidget(self.register_email_lineEdit)
        self.register_password_lineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.register_password_lineEdit.setFont(font)
        self.register_password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.register_password_lineEdit.setObjectName("register_password_lineEdit")
        self.verticalLayout_4.addWidget(self.register_password_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.frame)
        self.checkBox = QtWidgets.QCheckBox(self.registerPage)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QCheckBox{\n"
"    padding-bottom:20px;\n"
"}\n"
"\n"
"")
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.register_pushButton = QtWidgets.QPushButton(self.registerPage)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.register_pushButton.setFont(font)
        self.register_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.register_pushButton.setStyleSheet("")
        self.register_pushButton.setObjectName("register_pushButton")
        self.verticalLayout_3.addWidget(self.register_pushButton, 0, QtCore.Qt.AlignHCenter)
        self.to_login = QtWidgets.QPushButton(self.registerPage)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setUnderline(True)
        self.to_login.setFont(font)
        self.to_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.to_login.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    color: rgb(173, 65, 255);\n"
"\n"
"}")
        self.to_login.setObjectName("to_login")
        self.verticalLayout_3.addWidget(self.to_login, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.registerPage)
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.loginPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.loginPage)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/img/profile-w.png"))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.loginPage)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(245, 245, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.loginPage)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(245, 245, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.frame_2 = QtWidgets.QFrame(self.loginPage)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.email_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.email_lineEdit.setFont(font)
        self.email_lineEdit.setStyleSheet("")
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.verticalLayout_5.addWidget(self.email_lineEdit)
        self.password_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.password_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout_5.addWidget(self.password_lineEdit)
        self.verticalLayout_6.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.login_pushButton = QtWidgets.QPushButton(self.loginPage)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setObjectName("login_pushButton")
        self.verticalLayout_6.addWidget(self.login_pushButton, 0, QtCore.Qt.AlignHCenter)
        self.to_register = QtWidgets.QPushButton(self.loginPage)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setUnderline(True)
        self.to_register.setFont(font)
        self.to_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.to_register.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    color: rgb(173, 65, 255);\n"
"\n"
"}")
        self.to_register.setObjectName("to_register")
        self.verticalLayout_6.addWidget(self.to_register, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.loginPage)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.footer_frame = QtWidgets.QFrame(self.centralwidget)
        self.footer_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.verticalLayout.addWidget(self.footer_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sign Up"))
        self.label_2.setText(_translate("MainWindow", "Sign Up"))
        self.label_3.setText(_translate("MainWindow", "Enter your information below"))
        self.name_lineEdit.setPlaceholderText(_translate("MainWindow", "Name"))
        self.surname_lineEdit.setPlaceholderText(_translate("MainWindow", "Surname"))
        self.register_email_lineEdit.setPlaceholderText(_translate("MainWindow", "E-mail"))
        self.register_password_lineEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.checkBox.setText(_translate("MainWindow", "Agree with our terms"))
        self.register_pushButton.setText(_translate("MainWindow", "Register"))
        self.to_login.setText(_translate("MainWindow", "Already registered? Login"))
        self.label_4.setText(_translate("MainWindow", "Log In"))
        self.label_6.setText(_translate("MainWindow", "Enter your information below"))
        self.email_lineEdit.setPlaceholderText(_translate("MainWindow", "E-mail"))
        self.password_lineEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.login_pushButton.setText(_translate("MainWindow", "Login"))
        self.to_register.setText(_translate("MainWindow", "Not registered? Register"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
